### ISSUE TITLE
Zombie tests fail after upgrading jQuery from 1.11.3 to 1.12.2

### ISSUE THREAD

**Issue by jlchereau** [Memba/Memba-Blog#91]
```
TypeError: j.getClientRects is not a function
    at k (http://code.jquery.com/jquery-1.12.2.min.js:3:26891)
    at Object.n.extend.pixelMarginRight (http://code.jquery.com/jquery-1.12.2.min.js:3:25936)
    at a.getComputedStyle.Sa (http://code.jquery.com/jquery-1.12.2.min.js:3:27544)
    at Function.n.extend.css (http://code.jquery.com/jquery-1.12.2.min.js:3:30957)
    at Object.n.cssHooks.(anonymous function).get (http://code.jquery.com/jquery-1.12.2.min.js:3:31155)
    at Function.n.extend.css (http://code.jquery.com/jquery-1.12.2.min.js:3:30929)
    at http://code.jquery.com/jquery-1.12.2.min.js:5:534
    at Y (http://code.jquery.com/jquery-1.12.2.min.js:3:4661)
    at n.fn.(anonymous function) [as width] (http://code.jquery.com/jquery-1.12.2.min.js:5:305)
    at HTMLDocument.<anonymous> (http://localhost:3000/support/assets/home.bundle.js?v=undefined:3:2793)
    in http://localhost:3000/support/
```

See https://travis-ci.org/Memba/Memba-Blog/jobs/116880464

Defect submitted to https://github.com/assaf/zombie/issues/1031

**Comment by jlchereau** [comment]
We have replaced Zombie with Selenium
